<?php /* @var $block \DevStone\UsageCalculator\Block\Catalog\Product\Usage */ ?>
<?php if ($block->getProduct()->isSaleable() ):?>
<div id="usages-container" class="usages-container field">
    <button id="usage-button" class="cta-button" title="<?= __('License Image is a type of “renting” of an image for a specific use; examples include licensing an image for the cover of a book, an illustration for a magazine article, or use of an image in an evangelistic handbill.') ?>">
        <span class="calc-icon">&nbsp;</span>
        <span class="button-main">
            <span><?= __('License Image') ?></span>
            <span class="button-small"> <?= __('Download - price based on use.') ?></span>
        </span>
    </button>
    <div class="usages-container-inner">
    <button id="usage-button-close">
        <?= __('Close') ?>
    </button>
    <legend class="legend usages-title"><?= __('License Pricing Calculator') ?></legend>
    <p><?= __('Select options from the drop down menu to calculate a price to use this image.') ?></p>

    <div class="control" id="downloadable-usages-list"
         data-mage-init='{"usage":{
             "categorySelectElement":"#usage_category",
             "allElements":"#usages_all",
             "config":<?= /* @escapeNotVerified */ $block->getJsonConfig() ?>}
         }'
         data-container-for="downloadable-usages">
        <div class="field active">
            <label class="label" for="usage_category">
                <span><?= __('Choose Category') ?>:</span> <a href="#" data-less="<?= __('less info') ?>" tabindex="-1"><?= __('more info') ?></a>
            </label>
            <div class="help-text">
                <?= __('Choose a category to see the specific usages available.') ?>
            </div>
            <div class="control">
                <?= $block->getCategoriesSelectHtml() ?>
            </div>
        </div>
        <?php if(count( $block->getPreviousCategories() ) ): ?>
            <div class="category-container field" style="display:none;" id="category_container_previous">
                <label class="label" for="usage_previous_usages">
                    <span><?= __('Previous Usage') ?>:</span> <a href="#" data-less="<?= __('less info') ?>" tabindex="-1"><?= __('more info') ?></a>
                </label>
                <div class="help-text">
                    <?= __('Choose a previousl usage to use it for available usages.') ?>
                </div>
                <div class="control">
                    <?= $block->getPreviousSelectHtml() ?>
                </div>
            </div>
        <?php endif; ?>
        <?php foreach ($block->getCategories() as $category):  ?>
            <?php $usages = $block->getUsages($category) ?>

            <div class="category-container field" style="display:none;" id="category_container_<?= $category->getId() ?>">
                <label class="label" for="usage_<?= $category->getId() ?>_usages">
                    <span><?= __('Specific Usage') ?>:</span> <a href="#" data-less="<?= __('less info') ?>" tabindex="-1"><?= __('more info') ?></a>
                </label>
                <div class="help-text">
                    <?= __('Choose the usage which best describes how you intend to use the image.') ?>
                </div>
                <div class="control">
                    <?= $block->getUsagesSelectHtml($usages, $category); ?>
                </div>
            </div>

            <?php foreach ($usages as $usage): ?>
                <div class="usage-container" style="display:none;" id="usage_container_<?= $usage->getId() ?>">
                <?php foreach ($usage->getOptions() as $_option): ?>

                    <?= $block->getOptionHtml($_option) ?>

                <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        <?php endforeach; ?>
    </div>
    <span id="usages-advice-container"></span>
    </div>
</div>
<?php endif; ?>
