<?php /* @var $block \DevStone\UsageCalculator\Block\Catalog\Product\Usage */ ?>


			<button id="usage-button" class="cta-button" title="<?= __('License Image is a type of “renting” of an image for a specific use; examples include licensing an image for the cover of a book, an illustration for a magazine article, or use of an image in an evangelistic handbill.') ?>">
				<span class="calc-icon">&nbsp;</span>
				<span class="button-main">
            <span><?= __('License Image') ?></span>
            <span class="button-small"> <?= __('Download - price based on use.') ?></span>
        </span>
			</button>
		<div class="usages-container-inner" style="display: none;">
			<button id="usage-button-close">
				<?= __('Close') ?>
			</button>
			<legend class="legend usages-title"><?= __('License Pricing Calculator') ?></legend>
			<p><?= __('Select options from the drop down menu to calculate a price to use this image.') ?></p>

			<div class="control" id="downloadable-usages-list"
			     data-mage-init='{"usage":{
             "categorySelectElement":"#usage_category",
             "allElements":"#usages_all"}
         }'
			     data-container-for="downloadable-usages">
				<div class="field active">
					<label class="label" for="usage_category">
						<span><?= __('Choose Category') ?>:</span> <a href="#" data-less="<?= __('less info') ?>" tabindex="-1"><?= __('more info') ?></a>
					</label>
					<div class="help-text">
						<?= __('Choose a category to see the specific usages available.') ?>
					</div>
					<div class="control">
						<?= $block->getCategoriesSelectHtml() ?>
					</div>
				</div>
				<?php if(count( $block->getPreviousCategories() ) ): ?>
					<div class="category-container field" style="display:none;" id="category_container_previous">
						<label class="label" for="usage_previous_usages">
							<span><?= __('Previous Usage') ?>:</span> <a href="#" data-less="<?= __('less info') ?>" tabindex="-1"><?= __('more info') ?></a>
						</label>
						<div class="help-text">
							<?= __('Choose a previous calculation from your order history.') ?>
						</div>
						<div class="control">
							<?= $block->getPreviousSelectHtml() ?>
						</div>
					</div>
				<?php endif; ?>
				<?= $block->getChildHtml('all.usages'); ?>
				<?= $block->getChildHtml('custom.usages'); ?>
			</div>
			<span id="usages-advice-container"></span>
		</div>


