<?php
/** @var \DevStone\UsageCalculator\Block\Adminhtml\Customer\AssignCustomers $block */

/** @var \DevStone\UsageCalculator\Block\Adminhtml\Customer\Tab\Customer $blockGrid */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php if ($block->showGrid()): ?>
    <?= $block->getGridHtml() ?>
    <input type="hidden" name="usage_customers" id="in_usage_customers" data-form-part="devstone_usagecalculator_usage_form" value="" />
    <script type="text/x-magento-init">
        {
            "*": {
                "DevStone_UsageCalculator/js/components/select-customer": {
                    "selectedCustomers": <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                    "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
                }
            }
        }
    </script>
    <script>
        require('mage/apply/main').apply();
    </script>
<?php endif; ?>