<?php /* @var $block \DevStone\UsageCalculator\Block\Catalog\Product\Usage */ ?>
<?php foreach ($block->getCategories() as $category):  ?>
	<?php $usages = $block->getUsages($category) ?>

    <div class="category-container field" style="display:none;" id="category_container_<?= $category->getId() ?>">
        <label class="label" for="usage_<?= $category->getId() ?>_usages">
            <span><?= __('Specific Usage') ?>:</span> <a href="#" data-less="<?= __('less info') ?>" tabindex="-1"><?= __('more info') ?></a>
        </label>
        <div class="help-text">
			<?= __('Choose the usage which best describes how you intend to use the image.') ?>
        </div>
        <div class="control">
			<?= $block->getUsagesSelectHtml($usages, $category); ?>
        </div>
    </div>

	<?php foreach ($usages as $usage): ?>
        <div class="usage-container" style="display:none;" id="usage_container_<?= $usage->getId() ?>">
			<?php foreach ($usage->getOptions() as $_option): ?>

				<?= $block->getOptionHtml($_option) ?>

			<?php endforeach; ?>
			<?php if ($usage->getAdminNote()): ?>
                <div class="usage-admin-note" style="color: #ff0000; font-weight: bold; padding: 10px 0; margin: 10px 0; border-top: 1px solid #ddd; border-bottom: 1px solid #ddd;">
                    <?= $block->escapeHtml($usage->getAdminNote()) ?>
                </div>
            <?php endif; ?>
        </div>
	<?php endforeach; ?>
<?php endforeach; ?>